logging:
  file:
    name: college_compendium.log
    path: logs
  level:
    root: INFO
    '[com.collegecompendium]': DEBUG
server:
  port: 8080
  ssl:
    enabled: false
spring:
  web:
    resources:
      cache:
        cachecontrol:
          no-store: true