logging:
  file:
    name: college_compendium.log
    path: logs
  level:
    root: INFO
    '[com.collegecompendium]': TRACE
spring:
  profiles:
    active:
    - dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-yrjc5x2ila2084mu.us.auth0.com/
